-- V13: Seed additional categories for JSON-backed question sets
-- Generated by scripts/generate_question_seed_migrations.py

INSERT INTO categories (id, type, slug_tr, slug_en, title_tr, title_en, description_tr, description_en, icon, sort_order, active)
VALUES
  ('mobile', 'POSITION', 'mobile-developer-mulakat-sorulari', 'mobile-interview-questions', 'Mobile Developer', 'Mobile Developer', 'Mobil uygulama geliştirme, mimari, performans ve platform temelleri', 'Mobile app development, architecture, performance, and platform fundamentals', 'Smartphone', 14, true),
  ('testing', 'TECHNICAL', 'testing-mulakat-sorulari', 'testing-interview-questions', 'Testing', 'Testing', 'Yazilim testi, otomasyon, kalite guvencesi ve test stratejileri', 'Software testing, automation, QA, and test strategy', 'TestTube', 15, true),
  ('linux', 'TECHNICAL', 'linux-mulakat-sorulari', 'linux-interview-questions', 'Linux', 'Linux', 'Linux komutlari, sistem yonetimi, prosesler ve dosya sistemi', 'Linux commands, system administration, processes, and file systems', 'Terminal', 16, true),
  ('git', 'TECHNICAL', 'git-mulakat-sorulari', 'git-interview-questions', 'Git', 'Git', 'Versiyon kontrolu, branching stratejileri ve Git is akislari', 'Version control, branching strategies, and Git workflows', 'GitBranch', 17, true),
  ('kotlin', 'LANGUAGE', 'kotlin-mulakat-sorulari', 'kotlin-interview-questions', 'Kotlin Developer', 'Kotlin Developer', 'Kotlin dili, coroutine, null safety ve modern JVM gelistirme', 'Kotlin language, coroutines, null safety, and modern JVM development', 'Code2', 18, true),
  ('swift', 'LANGUAGE', 'swift-mulakat-sorulari', 'swift-interview-questions', 'Swift Developer', 'Swift Developer', 'Swift dili, ARC, protocol, concurrency ve iOS odakli gelistirme', 'Swift language, ARC, protocols, concurrency, and iOS-focused development', 'Code', 19, true),
  ('data-engineer', 'POSITION', 'data-engineer-mulakat-sorulari', 'data-engineer-interview-questions', 'Data Engineer', 'Data Engineer', 'ETL, veri platformlari, veri ambarlari ve dagitik veri isleme', 'ETL, data platforms, data warehouses, and distributed data processing', 'DatabaseZap', 20, true),
  ('cyber-security-specialist', 'POSITION', 'cyber-security-specialist-mulakat-sorulari', 'cyber-security-specialist-interview-questions', 'Cyber Security Specialist', 'Cyber Security Specialist', 'Siber guvenlik, tehdit tespiti, olay mudahalesi ve guvenlik mimarisi', 'Cybersecurity, threat detection, incident response, and security architecture', 'Shield', 21, true),
  ('business-analyst', 'POSITION', 'business-analyst-mulakat-sorulari', 'business-analyst-interview-questions', 'Business Analyst', 'Business Analyst', 'Requirement analysis, process improvement, stakeholder management ve is analizi', 'Requirement analysis, process improvement, stakeholder management, and business analysis', 'BriefcaseBusiness', 22, true)
ON CONFLICT (id) DO NOTHING;
