-- V8: Seed categories
-- Generated by scripts/generate-seed.ts

INSERT INTO categories (id, type, slug_tr, slug_en, title_tr, title_en, description_tr, description_en, icon, sort_order, active)
VALUES
  ('frontend', 'POSITION', 'frontend-mulakat-soruları', 'frontend-interview-questions', 'Frontend Developer', 'Frontend', 'React, JavaScript, CSS ve web temelleri', 'React, JavaScript, CSS and modern web development', 'Monitor', 0, true),
  ('backend', 'POSITION', 'backend-developer-mulakat-soruları', 'backend-interview-questions', 'Backend Developer', 'Backend', 'REST API, Node.js, güvenlik ve mimari', 'REST APIs, architecture, security and server-side development', 'Server', 1, true),
  ('devops', 'POSITION', 'devops-mulakat-soruları', 'devops-interview-questions', 'DevOps Engineer', 'DevOps', 'Docker, Kubernetes, CI/CD ve altyapı', 'Docker, Kubernetes, CI/CD and infrastructure', 'Container', 2, true),
  ('database', 'TECHNICAL', 'veritabani-mulakat-soruları', 'database-interview-questions', 'Veritabanı', 'Database', 'SQL, NoSQL, ACID, performans ve tasarım', 'SQL, NoSQL, ACID, performance and schema design', 'Database', 3, true),
  ('algorithms', 'TECHNICAL', 'algoritmalar-mulakat-soruları', 'algorithms-interview-questions', 'Algoritmalar', 'Algorithms', 'Veri yapıları, Big O ve temel algoritmalar', 'Data structures, Big O, and classic algorithm patterns', 'GitBranch', 4, true),
  ('system-design', 'TECHNICAL', 'sistem-tasarimi-mulakat-soruları', 'system-design-interview-questions', 'Sistem Tasarımı', 'System Design', 'Ölçeklendirme, mimari ve distributed sistemler', 'Scalability, distributed systems and high-availability architecture', 'Network', 5, true),
  ('hr', 'POSITION', 'ik-mulakat-soruları', 'hr-interview-questions', 'İK Mülakatı', 'İK Mülakatı', 'Davranışsal sorular, iletişim ve soft skills', '', 'Users', 6, true),
  ('javascript', 'LANGUAGE', 'javascript-mulakat-soruları', 'javascript-interview-questions', 'JavaScript Developer', 'JavaScript Developer', 'ES6+, asenkron programlama, prototip zinciri ve tarayıcı API''leri', 'ES6+, async programming, prototype chain and browser APIs', 'Braces', 7, true),
  ('python', 'LANGUAGE', 'python-mulakat-soruları', 'python-interview-questions', 'Python Developer', 'Python Developer', 'Python temelleri, OOP, dekoratörler, async ve veri yapıları', 'Python fundamentals, OOP, decorators, async, and data structures', 'Code', 8, true),
  ('java', 'LANGUAGE', 'java-mulakat-soruları', 'java-interview-questions', 'Java Developer', 'Java Developer', 'JVM, OOP, Collections, Stream API ve modern Java', 'JVM, OOP, Collections, Stream API and modern Java', 'Coffee', 9, true),
  ('csharp', 'LANGUAGE', 'csharp-mulakat-soruları', 'csharp-interview-questions', 'C# Developer', 'C# Developer', '.NET ekosistemi, LINQ, async/await ve modern C# özellikleri', '.NET ecosystem, LINQ, async/await and modern C# features', 'Hash', 10, true),
  ('go', 'LANGUAGE', 'go-mulakat-soruları', 'go-interview-questions', 'Go Developer', 'Go Developer', 'Goroutine, channel, interface, hata yönetimi ve Go idioms', 'Goroutines, channels, interfaces, error handling and Go idioms', 'Zap', 11, true),
  ('rust', 'LANGUAGE', 'rust-mulakat-soruları', 'rust-interview-questions', 'Rust Developer', 'Rust Developer', 'Ownership, borrowing, lifetime, trait ve sistem programlama', 'Ownership, borrowing, lifetimes, traits and systems programming', 'Shield', 12, true),
  ('fullstack', 'POSITION', 'fullstack-mulat-soruları', 'fullstack-interview-questions', 'Full Stack Developer', 'Full Stack Developer', 'Frontend, backend, veritabanı ve deployment bir arada', 'Frontend, backend, database and deployment combined', 'Layers', 13, true);
